name: 13-caching.yml
on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true
      node-version:
        type: choice
        description: Node version
        options:
          - 18.x
          - 20.x
          - 21.x
          - 22.x
          - 24.x
        default: 24.x

jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    outputs:
      deps-cache-key: ${{steps.cache-key.outputs.CACHE_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{inputs.node-version}}

      - name: Calculate cache key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ hashFiles('package-log.json') }}" >> "$GITHUB_OUTPUTS"
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{inputs.use-cache}}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    needs: install-deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{inputs.node-version}}
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{inputs.use-cache}}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{needs.install-deps.outputs.deps-cache-key}}
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
